// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.types.ts
// For now, we'll create a basic structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          phone: string | null
          timezone: string
          subscription_tier: 'starter' | 'pro' | 'enterprise'
          subscription_status: 'active' | 'cancelled' | 'past_due' | 'trialing'
          stripe_customer_id: string | null
          client_limit: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone?: string | null
          timezone?: string
          subscription_tier?: 'starter' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'cancelled' | 'past_due' | 'trialing'
          stripe_customer_id?: string | null
          client_limit?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone?: string | null
          timezone?: string
          subscription_tier?: 'starter' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'cancelled' | 'past_due' | 'trialing'
          stripe_customer_id?: string | null
          client_limit?: number
          created_at?: string
          updated_at?: string
        }
      }
      clients: {
        Row: {
          id: string
          trainer_id: string
          name: string
          email: string | null
          phone: string | null
          photo_url: string | null
          notes: string | null
          goals: string | null
          medical_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          trainer_id: string
          name: string
          email?: string | null
          phone?: string | null
          photo_url?: string | null
          notes?: string | null
          goals?: string | null
          medical_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          trainer_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          photo_url?: string | null
          notes?: string | null
          goals?: string | null
          medical_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      appointments: {
        Row: {
          id: string
          trainer_id: string
          client_id: string
          scheduled_at: string
          duration_minutes: number
          status: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          trainer_id: string
          client_id: string
          scheduled_at: string
          duration_minutes?: number
          status?: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          trainer_id?: string
          client_id?: string
          scheduled_at?: string
          duration_minutes?: number
          status?: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      workouts: {
        Row: {
          id: string
          trainer_id: string
          name: string
          description: string | null
          exercises: Json
          is_template: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          trainer_id: string
          name: string
          description?: string | null
          exercises?: Json
          is_template?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          trainer_id?: string
          name?: string
          description?: string | null
          exercises?: Json
          is_template?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          trainer_id: string
          client_id: string
          amount: number
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          due_date: string | null
          paid_at: string | null
          stripe_payment_intent_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          trainer_id: string
          client_id: string
          amount: number
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          due_date?: string | null
          paid_at?: string | null
          stripe_payment_intent_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          trainer_id?: string
          client_id?: string
          amount?: number
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          due_date?: string | null
          paid_at?: string | null
          stripe_payment_intent_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      workout_sessions: {
        Row: {
          id: string
          trainer_id: string
          client_id: string
          workout_id: string | null
          completed_at: string
          exercises_completed: Json
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          trainer_id: string
          client_id: string
          workout_id?: string | null
          completed_at?: string
          exercises_completed?: Json
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          trainer_id?: string
          client_id?: string
          workout_id?: string | null
          completed_at?: string
          exercises_completed?: Json
          notes?: string | null
          created_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          invoice_id: string
          trainer_id: string
          client_id: string
          amount: number
          stripe_payment_id: string
          created_at: string
        }
        Insert: {
          id?: string
          invoice_id: string
          trainer_id: string
          client_id: string
          amount: number
          stripe_payment_id: string
          created_at?: string
        }
        Update: {
          id?: string
          invoice_id?: string
          trainer_id?: string
          client_id?: string
          amount?: number
          stripe_payment_id?: string
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          trainer_id: string
          type: 'appointment_upcoming' | 'appointment_reminder' | 'invoice_overdue' | 'invoice_due_soon' | 'client_birthday' | 'workout_reminder' | 'system_update'
          title: string
          message: string
          related_id: string | null
          related_type: string | null
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          trainer_id: string
          type: 'appointment_upcoming' | 'appointment_reminder' | 'invoice_overdue' | 'invoice_due_soon' | 'client_birthday' | 'workout_reminder' | 'system_update'
          title: string
          message: string
          related_id?: string | null
          related_type?: string | null
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          trainer_id?: string
          type?: 'appointment_upcoming' | 'appointment_reminder' | 'invoice_overdue' | 'invoice_due_soon' | 'client_birthday' | 'workout_reminder' | 'system_update'
          title?: string
          message?: string
          related_id?: string | null
          related_type?: string | null
          read_at?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_trainer_stats: {
        Args: {
          p_trainer_id: string
        }
        Returns: {
          total_clients: number
          active_clients: number
          total_appointments: number
          upcoming_appointments: number
          total_revenue: number
          monthly_revenue: number
        }[]
      }
      get_upcoming_appointments: {
        Args: {
          p_trainer_id: string
          p_days?: number
        }
        Returns: {
          id: string
          client_id: string
          client_name: string
          scheduled_at: string
          duration_minutes: number
          status: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes: string | null
        }[]
      }
    }
  }
}


